/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    ElAside: (typeof import("element-plus/es"))["ElAside"]
    ElAvatar: (typeof import("element-plus/es"))["ElAvatar"]
    ElBacktop: (typeof import("element-plus/es"))["ElBacktop"]
    ElBreadcrumb: (typeof import("element-plus/es"))["ElBreadcrumb"]
    ElBreadcrumbItem: (typeof import("element-plus/es"))["ElBreadcrumbItem"]
    ElButton: (typeof import("element-plus/es"))["ElButton"]
    ElContainer: (typeof import("element-plus/es"))["ElContainer"]
    ElDialog: (typeof import("element-plus/es"))["ElDialog"]
    ElDivider: (typeof import("element-plus/es"))["ElDivider"]
    ElDropdown: (typeof import("element-plus/es"))["ElDropdown"]
    ElDropdownItem: (typeof import("element-plus/es"))["ElDropdownItem"]
    ElDropdownMenu: (typeof import("element-plus/es"))["ElDropdownMenu"]
    ElEmpty: (typeof import("element-plus/es"))["ElEmpty"]
    ElForm: (typeof import("element-plus/es"))["ElForm"]
    ElFormItem: (typeof import("element-plus/es"))["ElFormItem"]
    ElHeader: (typeof import("element-plus/es"))["ElHeader"]
    ElIcon: (typeof import("element-plus/es"))["ElIcon"]
    ElInput: (typeof import("element-plus/es"))["ElInput"]
    ElMain: (typeof import("element-plus/es"))["ElMain"]
    ElMenu: (typeof import("element-plus/es"))["ElMenu"]
    ElMenuItem: (typeof import("element-plus/es"))["ElMenuItem"]
    ElOption: (typeof import("element-plus/es"))["ElOption"]
    ElScrollbar: (typeof import("element-plus/es"))["ElScrollbar"]
    ElSelect: (typeof import("element-plus/es"))["ElSelect"]
    ElSubMenu: (typeof import("element-plus/es"))["ElSubMenu"]
    ElSwitch: (typeof import("element-plus/es"))["ElSwitch"]
    ElTooltip: (typeof import("element-plus/es"))["ElTooltip"]
    RouterLink: (typeof import("vue-router"))["RouterLink"]
    RouterView: (typeof import("vue-router"))["RouterView"]
    Screenfull: (typeof import("./src/components/Screenfull/index.vue"))["default"]
    SearchFooter: (typeof import("./src/components/SearchMenu/SearchFooter.vue"))["default"]
    SearchMenu: (typeof import("./src/components/SearchMenu/index.vue"))["default"]
    SearchModal: (typeof import("./src/components/SearchMenu/SearchModal.vue"))["default"]
    SearchResult: (typeof import("./src/components/SearchMenu/SearchResult.vue"))["default"]
    SvgIcon: (typeof import("./src/components/SvgIcon/index.vue"))["default"]
  }
}
